x = "Hello World" # string 
x = 50  # integer 
x = 60.5  # float 
x = 3j  # complex 
x = ["geeks", "for", "geeks"]  # list  
x = ("geeks", "for", "geeks")  # tuple 
x = {"name": "Suraj", "age": 24} # dict 
x = {"geeks", "for", "geeks"} # set 
x = True  # bool 
x = b"Geeks" # binary 