#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:

#By considering the terms in the Fibonacci sequence whose values do not exceed four million find the sum of the even valued terms.
#4.000.000

from tkinter import TOP

#A function that checks elements if it's even
def evenNumber_decorator(func):
    def wrapper(sayi):
        fibonacci_list = func(sayi)  
        even_number_list = [i for i in fibonacci_list if i % 2 == 0]  
        return even_number_list
    return wrapper

#A decorator
@evenNumber_decorator
#A function to create a fib list  (I don't know which fib list index not over 4000000 so I add extra if statement) 
def Fibonacci(sayi):
    fibonacci_list=[1,1]
    
    for i in range(2, sayi):
        next_fibonacci = fibonacci_list[i-1] + fibonacci_list[i-2]
        if next_fibonacci > 4000000: 
            print(i)
            break
        
        fibonacci_list.append(next_fibonacci)
        
    return fibonacci_list

#Putting all elements into a list
even_fib_list=Fibonacci(39)
#To find total sum of list
total_sum = sum(even_fib_list)

print(total_sum)
